name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: coursier/cache-action@v6
      - name: Set up JDK 14
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Run tests
        run: csbt headerCheck compile test
